version: "3"

volumes:
  dbdata:

services:
  db:
    image: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  web:
    build: .
    command: uwsgi --socket :8000 --module everybody_recommend.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    tty: true
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - web