# Generated by Django 2.2 on 2019-04-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='コメント内容')),
                ('good_count', models.IntegerField(default=0, verbose_name='グッド数')),
                ('bad_count', models.IntegerField(default=0, verbose_name='バッド数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='質問タイトル')),
                ('reason', models.TextField(verbose_name='質問理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='おすすめ名')),
                ('reason', models.TextField(verbose_name='おすすめ理由')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='イメージ')),
                ('link', models.URLField(blank=True, null=True, verbose_name='リンク')),
                ('good_count', models.IntegerField(default=0, verbose_name='グッド数')),
                ('bad_count', models.IntegerField(default=0, verbose_name='バッド数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='対象質問')),
            ],
        ),
    ]
