# Generated by Django 2.2 on 2019-08-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='is_best',
            field=models.BooleanField(default=False, verbose_name='ベストレコメンドフラグ'),
        ),
    ]
