# Generated by Django 2.2 on 2019-09-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_bad_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='bad_count',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='good_count',
        ),
    ]
