# Generated by Django 2.2 on 2019-09-08 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_auto_20190908_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='recommend',
        ),
        migrations.RemoveField(
            model_name='good',
            name='user',
        ),
        migrations.AddField(
            model_name='recommend',
            name='bads',
            field=models.ManyToManyField(related_name='bads', to=settings.AUTH_USER_MODEL, verbose_name='bad'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='goods',
            field=models.ManyToManyField(related_name='goods', to=settings.AUTH_USER_MODEL, verbose_name='good'),
        ),
        migrations.DeleteModel(
            name='Bad',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
    ]
